id: A8B8BC2CF
title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
type: translation
pechas:
- IE644E441
- I34C99099
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:44.586160
  last_modified_at: 2023-01-04 12:12:44.586172
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IE644E441/A9E8: A3E5
  I34C99099/3BB5: A3E5
